### ISSUE TITLE
Redacting phone number not working 100%

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/libpastelog#12]
found in a gist 

```
E/AndroidRuntime( 2247): java.lang.AssertionError: Session didn't get migrated: (0,+000000000000:1)
E/AndroidRuntime( 2247): 	at org.thoughtcrime.securesms.crypto.storage.TextSecureSessionStore.loadSession(TextSecureSessionStore.java:71)
```
(digits replaced with 0s)

` throw new AssertionError("Session didn't get migrated: (" + versionMarker + "," + address + ")");`

criticalBug = (address == phoneNumber)

**Comment by mcginty** [comment]
you sure this gist was created with the log submission built in to Signal? the regex Scrubber uses should match that...

**Comment by McLoo** [comment]
:disappointed: stupid me 
seems to be an plain adb logcat

**Comment by mcginty** [comment]
all good, sorry it took a bit to respond
