### ISSUE TITLE
Unredacted phone number in debug log after PhoneNumberFormatter failure

### ISSUE THREAD

**Issue by brad2014** [WhisperSystems/libpastelog#14]
I noticed in the last line of the Android debug log of WhisperSystems/Signal-Desktop#649 that a unparseable phone number is logged on Android without redaction. Just thought I'd note it.

02-01 13:27:22.986: W/EarlyReceiptCache(19337): Checking early receipts (1454329639749, +82604946527386932081): null

**Comment by 2-4601** [comment]
I'd guess @tobiasgeibinger used adb to capture the original log and manually replaced most of the numbers (to match the Deskto log perhaps?).
The _Submit debug log_ capture within Signal Android does not use the form `+[REDACTED]666` but `+********66`

The line:
`02-01 13:27:22.986: W/EarlyReceiptCache(19337): Checking early receipts (1454329639749, +82604946527386932081): null`
is weird and definitely not a real phone number

I tested and it appears you get those weird long numbers every time when you send a message in a group.

**Comment by eosrei** [comment]
@brad2014 I just noticed the same thing, apparently it's intentional: https://github.com/WhisperSystems/Signal-Android/issues/5204

**Comment by agrajaghh** [comment]
If you use adb nothing is redacted, but if you use settings -> advanced -> submit debug log, libpastelog is redacting phone numbers. If you're still finding them in these logs, please open a new issue here
